blog/urls.py
from django.conf.urls import url

from . import views


app_name = "blog"

urlpatterns = [
    url(r"^tag/(?P<tag>[-\w]+)/", views.tag_view, name="tag"),
    url(
        r"^category/(?P<category>[-\w]+)/feed/$",
        views.LatestCategoryFeed(),
        name="category_feed",
    ),
    url(r"^category/(?P<category>.+)/", views.category_view, name="category"),
    url(r"^locale/(?P<locale>[-\w]+)/", views.locale_view, name="locale"),
    url(r"^author/(?P<author>[-\w]+)/", views.author_view, name="author"),
    url(
        r"(?P<blog_slug>[\w-]+)/rss.*/",
        views.LatestEntriesFeed(),
        name="latest_entries_feed",
    ),
    url(
        r"(?P<blog_slug>[\w-]+)/atom.*/",
        views.LatestEntriesFeedAtom(),
        name="latest_entries_feed_atom",
    ),
]

blog/models.py
import datetime

from bs4 import BeautifulSoup
from compressor.css import CssCompressor
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.core.paginator import Paginator
from django.db import models
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from django.utils.html import format_html
from modelcluster.fields import ParentalKey
from modelcluster.tags import ClusterTaggableManager
from taggit.models import Tag
from taggit.models import TaggedItemBase
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.admin.edit_handlers import FieldRowPanel
from wagtail.admin.edit_handlers import InlinePanel
from wagtail.admin.edit_handlers import MultiFieldPanel
from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.core import blocks
from wagtail.core import hooks
from wagtail.core.fields import RichTextField
from wagtail.core.fields import StreamField
from wagtail.core.models import Page
from wagtail.core.templatetags.wagtailcore_tags import richtext
from wagtail.documents import get_document_model_string
from wagtail.images import get_image_model_string
from wagtail.images.blocks import ImageChooserBlock
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index
from wagtail.snippets.models import register_snippet
from wagtail_footnotes.blocks import RichTextBlockWithFootnotes

from home.models import ArticleBase
from migcontrol.utils import get_toc

# from django.utils.translation import ugettext_lazy as _


COMMENTS_APP = getattr(settings, "COMMENTS_APP", None)


def get_blog_context(context):
    """Get context data useful on all blog related pages"""
    context["authors"] = (
        get_user_model()
        .objects.filter(
            owned_pages__live=True, owned_pages__content_type__model="blogpage"
        )
        .annotate(Count("owned_pages"))
        .order_by("-owned_pages__count")
    )
    context["all_categories"] = BlogCategory.objects.all()
    context["root_categories"] = (
        BlogCategory.objects.filter(
            parent=None,
        )
        .prefetch_related(
            "children",
        )
        .annotate(
            blog_count=Count("blogpage"),
        )
    )
    return context


class BlogIndexPage(ArticleBase, Page):
    template = "blog/index.html"

    @property
    def blogs(self):
        # Get list of blog pages that exist - we don't care which blog they
        # belong to for now, as blogs are not language sensitive
        blogs = BlogPage.objects.all().live()
        blogs = (
            blogs.order_by("-date")
            .select_related("owner")
            .prefetch_related(
                "tagged_items__tag",
                "categories",
                "categories__category",
            )
        )
        return blogs

    def get_context(  # noqa: max-complexity=14
        self,
        request,
        tag=None,
        category=None,
        author=None,
        locale=None,
        *args,
        **kwargs
    ):
        context = super(BlogIndexPage, self).get_context(request, *args, **kwargs)
        blogs = self.blogs

        if tag is None:
            tag = request.GET.get("tag")
        if tag:
            blogs = blogs.filter(tags__slug=tag)
        if category is None:  # Not coming from category_view in views.py
            if request.GET.get("category"):
                category = get_object_or_404(
                    BlogCategory, slug=request.GET.get("category")
                )
        if category:
            if not request.GET.get("category"):
                category = get_object_or_404(BlogCategory, slug=category)
            blogs = blogs.filter(categories__category__name=category)
        if author:
            blogs = blogs.filter(authors__icontains=author)
        if locale:
            blogs = blogs.filter(locale=locale)

        # Pagination
        page = request.GET.get("page")
        page_size = 12
        if hasattr(settings, "BLOG_PAGINATION_PER_PAGE"):
            page_size = settings.BLOG_PAGINATION_PER_PAGE

        if page_size is not None:
            paginator = Paginator(blogs, page_size)  # Show 10 blogs per page
            try:
                blogs = paginator.page(page)
            except PageNotAnInteger:
                blogs = paginator.page(1)
            except EmptyPage:
                blogs = paginator.page(paginator.num_pages)

        context["blogs"] = blogs
        context["category"] = category
        context["locale"] = locale
        context["categories"] = BlogCategory.objects.all()
        context["tag"] = tag
        context["author"] = author
        context["COMMENTS_APP"] = COMMENTS_APP
        context = get_blog_context(context)

        return context

    class Meta:
        verbose_name = "Blog index"

    subpage_types = ["blog.BlogPage"]


@register_snippet
class BlogCategory(models.Model):
    name = models.CharField(max_length=80, verbose_name=("Category Name"))
    slug = models.SlugField(unique=True, max_length=80)
    parent = models.ForeignKey(
        "self",
        blank=True,
        null=True,
        related_name="children",
        help_text=(
            "Categories, unlike tags, can have a hierarchy. You might have a "
            "Jazz category, and under that have children categories for Bebop"
            " and Big Band. Totally optional."
        ),
        on_delete=models.CASCADE,
    )
    description = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "Blog Category"
        verbose_name_plural = "Blog Categories"

    panels = [
        FieldPanel("name"),
        FieldPanel("parent"),
        FieldPanel("description"),
    ]

    def __str__(self):
        return self.name

    def clean(self):
        if self.parent:
            parent = self.parent
            if self.parent == self:
                raise ValidationError("Parent category cannot be self.")
            if parent.parent and parent.parent == self:
                raise ValidationError("Cannot have circular Parents.")

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.name)
            count = BlogCategory.objects.filter(slug=slug).count()
            if count > 0:
                slug = "{}-{}".format(slug, count)
            self.slug = slug
        return super(BlogCategory, self).save(*args, **kwargs)


class BlogCategoryBlogPage(models.Model):
    category = models.ForeignKey(
        BlogCategory,
        related_name="+",
        verbose_name=("Category"),
        on_delete=models.CASCADE,
    )
    page = ParentalKey("BlogPage", related_name="categories")
    panels = [
        FieldPanel("category"),
    ]


class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey("BlogPage", related_name="tagged_items")


def limit_author_choices():
    """Legacy function to appease migration error."""
    return None


@register_snippet
class BlogTag(Tag):
    class Meta:
        proxy = True


class BlogPage(Page):
    body_richtext = RichTextField(
        verbose_name=("body (HTML)"),
        blank=True,
        features=[
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "bold",
            "italic",
            "ol",
            "ul",
            "hr",
            "link",
            "document-link",
            "image",
            "embed",
            "footnotes",
            "code",
            "superscript",
            "subscript",
            "strikethrough",
            "blockquote",
        ],
    )
    body_mixed = StreamField(
        [
            ("heading", blocks.CharBlock(classname="full title")),
            ("paragraph", RichTextBlockWithFootnotes()),
            ("image", ImageChooserBlock()),
        ],
        verbose_name="body (mixed)",
        blank=True,
        help_text="Avoiding this at first because data might be hard to migrate?",
    )

    add_toc = models.BooleanField(
        default=False,
        verbose_name=("Display TOC (Table Of Contents)"),
        help_text=("A TOC can be auto-generated"),
    )

    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)
    date = models.DateField(
        ("Post date"),
        default=datetime.datetime.today,
        help_text=(
            "This date may be displayed on the blog post. It is not "
            "used to schedule posts to go live at a later date."
        ),
    )
    header_image = models.ForeignKey(
        get_image_model_string(),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
        verbose_name=("Header image"),
    )
    authors = models.CharField(
        blank=True,
        null=True,
        verbose_name="author(s)",
        max_length=255,
        help_text="Mention author(s) by the name to be displayed",
    )

    search_fields = Page.search_fields + [
        index.SearchField("body_richtext"),
        index.SearchField("body_mixed"),
    ]
    blog_categories = models.ManyToManyField(
        BlogCategory, through=BlogCategoryBlogPage, blank=True
    )

    settings_panels = Page.settings_panels + [
        MultiFieldPanel(
            [
                FieldRowPanel(
                    [
                        FieldPanel("go_live_at"),
                        FieldPanel("expire_at"),
                    ],
                    classname="label-above",
                ),
            ],
            "Scheduled publishing",
            classname="publishing",
        ),
        FieldPanel("date"),
        FieldPanel("authors"),
    ]

    def get_body(self):
        if self.body_richtext:

blog/views.py
from django.conf import settings
from django.contrib.syndication.views import Feed
from django.shortcuts import get_object_or_404
from django.utils.feedgenerator import Atom1Feed
from wagtail.core.models.i18n import Locale

from .models import BlogCategory
from .models import BlogIndexPage
from .models import BlogPage


def tag_view(request, tag):
    index = BlogIndexPage.objects.first()
    return index.serve(request, tag=tag)


def category_view(request, category):
    index = BlogIndexPage.objects.first()
    return index.serve(request, category=category)


def locale_view(request, locale):
    index = BlogIndexPage.objects.first()
    locale = Locale.objects.get(language_code=locale)
    return index.serve(request, locale=locale)


def author_view(request, author):
    index = BlogIndexPage.objects.first()
    return index.serve(request, author=author)


class LatestEntriesFeed(Feed):
    """
    If a URL ends with "rss" try to find a matching BlogIndexPage
    and return its items.
    """

    def get_object(self, request, blog_slug):
        return get_object_or_404(BlogIndexPage, slug=blog_slug)

    def title(self, blog):
        if blog.seo_title:
            return blog.seo_title
        return blog.title

    def link(self, blog):
        return blog.full_url

    def description(self, blog):
        return blog.search_description

    def items(self, blog):
        num = getattr(settings, "BLOG_PAGINATION_PER_PAGE", 10)
        return blog.get_descendants().order_by("-blogpage__date")[:num]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.specific.body_richtext

    def item_link(self, item):
        return item.full_url

    def item_pubdate(self, blog):
        return blog.first_published_at


class LatestEntriesFeedAtom(LatestEntriesFeed):
    feed_type = Atom1Feed


class LatestCategoryFeed(Feed):
    description = "A Blog"

    def title(self, category):
        return "Blog: " + category.name

    def link(self, category):
        return "/blog/category/" + category.slug

    def get_object(self, request, category):
        return get_object_or_404(BlogCategory, slug=category)

    def items(self, obj):
        return BlogPage.objects.filter(categories__category=obj).order_by("-date")[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body_legacy

blog/templates/blog/blog_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}
{% load static %}

{% block before_content %}
  {% if self.header_image %}
  {% image self.header_image width-1680 as tmp_photo %}
    <div class="container-image-background" style="background-image: url('{{ tmp_photo.url }}');">
    </div>
  {% endif %}
{% endblock %}

{% block content %}
    {% include 'blog/blog_post.html' with blog=self %}
    {% include "wagtail_footnotes/includes/footnotes.html" %}
{% endblock %}

{% block sidebar %}
{% with self.get_toc as toc %}
{% if toc %}
<nav id="contents-toc" class="navbar navbar-light bg-light flex-column align-items-stretch p-3 sticky-md-top my-3">
  <a class="navbar-brand" href="#">Table of contents</a>
  <nav class="nav nav-pills flex-column">
  {% for section, children in toc %}
      {% include "migcontrol/includes/toc_section.html" with section=section children=children %}
  {% endfor %}
  </nav>
</nav>
{% endif %}
{% endwith %}
{% endblock %}

{% block extra_js %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/toc.js' %}"></script>
{% endblock %}

blog/templates/blog/blog_post.html
{% load wagtailcore_tags static %}
{% load i18n %}
{% load migcontrol_tags %}

<h1 class="migcontrol-page-title">{{ blog.title }}</h1>

{% if blog.date %}
    <p class="text-primary">
        <span class="fa fa-clock"></span>
        {{ blog.date|date:"F jS, Y" }}
        {% if blog.authors %}
        - {% trans "written by" %}: {{ blog.authors|default:"" }}
        {% endif %}
    </p>
{% endif %}


<div class="blog-body">
    {% richtext_footnotes blog.get_body %}
</div>


<div class="blog-post-meta">
    <div class="tags">
        {% if blog.tags.all %}
            Tags:
                {% for tag in blog.tags.all %}
                    <a href="{% url 'blog:tag' tag.slug %}/">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
        {% endif %}
    </div>
    <div class="tags-and-comments">
        {% if blog.categories.all %}
            Posted in
                {% for cat in blog.categories.all %}
                    <a href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
        {% endif %}

    </div>
</div>

blog/templates/blog/index.html
{% extends "base.html" %}
{% load i18n %}
{% load wagtailcore_tags static %}
{% load wagtailimages_tags %}

{% block sidebar %}
  <h1>{{ page.title }}</h1>

  <p>{% trans "Filter by language" %}</p>
  <p>
  {% for language_code, language_name in LANGUAGES %}
      {% get_language_info for language_code as lang %}
      {% language language_code %}
        <a class="badge {% if locale.language_code == language_code %}bg-dark{% else %}bg-secondary{% endif %}" href="{% url "blog:locale" locale=language_code %}">
          {{ language_name }}
        </a>
      {% endlanguage %}
  {% endfor %}
  </p>

  <p>{% trans "Filter by category" %}</p>
  <p>
  {% for list_category in categories %}
      <a class="badge rounded-pill {% if category == list_category %}bg-dark{% else %}bg-secondary{% endif %}" href="{% url "blog:category" category=list_category.slug %}">
        {{ list_category.name }}
      </a>
  {% endfor %}
  </p>

  {% for block in page.body %}
    {% include_block block %}
  {% endfor %}
{% endblock %}

{% block content %}
    {% if category %}
    <h1 class="migcontrol-page-title">{{ category }}</h1>
    {% elif tag %}
    <h1 class="migcontrol-page-title">Posts tagged with '{{ tag }}'</h1>
    {% endif %}

    {% if blogs %}

    <div class="row row-cols-1 row-cols-md-3 g-4 mt-4">

        {% for blog in blogs %}
          <div class="col">
          <div class="card h-100">
            {% if blog.header_image %}
            {% image blog.header_image fill-500x300 as tmp_photo %}
            <img class="card-img-top" src="{{ tmp_photo.url }}">
            {% else %}
            <img class="card-img-top" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ blog.title }}</h5>
              <p class="card-text"><small class="text-muted">{{ blog.date|date:"F jS, Y" }}</small></p>
              <p class="card-text">{{ blog.body_richtext|richtext|striptags|truncatewords_html:30 }}</p>
              <p class="card-text">
                <a href="{% pageurl blog %}" class="btn btn-primary">{% trans "Read more" %}</a>
              </p>
            </div>
          </div>
          </div>
        {% endfor %}

    </div>

    <div class="pagination btn-group">
    {% if blogs.has_next %}
      <a class="btn btn-outline-info" href="?page={{ blogs.next_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&amp;{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">&larr; {% trans "Older" %}</a>
    {% endif %}
    {% if blogs.has_previous %}
      <a class="btn btn-outline-info" href="?page={{ blogs.previous_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&amp;{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">{% trans "Newer" %} &rarr;</a>
    {% endif %}
    </div>

    {% else %}
        <p>There are currently no blog posts</p>
    {% endif %}
{% endblock %}